### ISSUE TITLE
Load maybe 20 paintings at a time and make the load more button :)

### ISSUE THREAD

**Issue by henrynavntoft** [henrynavntoft/full-stack-exam#22]
You have already done it once right?

**Comment by federico-barbieri** [comment]
I'll explain the flow **backwards** before closing this issue so we can look back at it if needed:

A request is made to the artworks endpoint. We used to fetch all of them. Now we are fetching 5 (since our db only fetches 50 artworks currently). This can easily be changed to 10, 20 or 100. We are also fetching the total number of artworks in the db so we can disable the btn once we reach that number. So now we are returning an array with 2 elements inside. Important to remember.

```
`router.get('/', async (req: Request, res: Response) => {
  const { page = 1 } = req.query; // Defaults to page 1 if no page is provided
  const pageSize = 5;

  try {
    const totalArtworks = await prisma.artwork.count();
    const artworks = await prisma.artwork.findMany({
      skip: (Number(page) - 1) * pageSize,
      take: pageSize,
    });
    res.json([ artworks, totalArtworks ]);
  } catch (error) {
    console.error("Error fetching artworks:", error);
    res.status(500).json({ error: "Failed to fetch artworks." });
  }
});
`
```


This call was made from the function **fetchArtworks**:

```
export const fetchArtworks = async (page = 1) => {
  const response = await axiosInstance.get(`/api/artworks?page=${page}`);
  
  const [artworks, totalArtworks] = response.data;

  return { artworks, totalArtworks };

};
```

In the **ArtworkList**, the component that is rendered both in the homepage and in the dashboard, we are using React Query to get the artworks and the amount of artworks in the db. They are called "data" until destructured:

```
  const {
    data,
    isLoading,
    isError,
    error,
    isFetching,
  } = useQuery({
    queryKey: ['artworks', page],
    queryFn: () => fetchArtworks(page),
    keepPreviousData: true,
  });
```

Now we will load **SetArt** with artworks and **isAllFetched** with a boolean. Note that if this is the first time, a.k.a. the first page, already load **setArt** with the artworks. This is important to avoid headaches:

```
useEffect(() => {
    if (data) {
      const { artworks, totalArtworks: total } = data;

    if (page === 1) {
      setArt(artworks); 
    } else {
      setArt((prevArtworks) => [...prevArtworks, ...artworks]); 
    }
    setTotalArtworks(total); 
  }
  }, [data, page]); 

  const isAllFetched = art.length >= totalArtworks; 
```

Finally, the button will base its text and state based on the elements we have been previously talking about, and it uses a very simple function that just adds a new page as a parameter, so this will trigger a re-render:

```
<button
        onClick={loadMoreArt}
        className="m-4 bg-primary text-primary-foreground px-4 py-2 rounded hover:bg-primary-dark"
        disabled={isFetching || isLoading || isAllFetched}
>
        {isFetching || isLoading ? 'Loading...' : isAllFetched ? 'All Artworks Loaded' : 'Load More'}
</button>
```

```
const loadMoreArt = () => {
    setPage((prevPage) => prevPage + 1); 
  };
```
